version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tasks_db
    environment:
      POSTGRES_USER: demian
      POSTGRES_PASSWORD: examen123
      POSTGRES_DB: tasks_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: